### ISSUE TITLE
Namespacing only, not working 

### ISSUE THREAD

**Issue by jitendravyas** [acss-io/grunt-atomizer#38]
I'm using this 

```
		atomizer: {
			        options: {
            namespace: '#atomic',
		},
			moduleshtml: {
				files: [
					{
						src: ['app/modules/**/*.html'],
						dest: 'app/styles/_atomizer.scss'
					}
				]
			}
		},
```

but i don't get everything wrapped inside #atomic id in output

**Comment by thierryk** [comment]
Did you try without the comma (`,`) after `#atomic`?

**Comment by jitendravyas** [comment]
Not sure why it was not working before but this works now.

```
		atomizer: {
			options: {
				namespace: '#atomic',
				configFile: 'app/styles/acss-config.js'
			},
			moduleshtml: {
				files: [
					{
						src: ['app/modules/**/*.html'],
						dest: 'app/styles/_atomizer.scss'
					}
				]
			}
		},
```

**Comment by thierryk** [comment]
That's because the comma (`,`) after `#atomic` is no longer a problem now that you have added an extra key/value pair. In other words, it would fail the same if you had a comma after `configFile: 'app/styles/acss-config.js'`.
