### ISSUE TITLE
How to integrate grunt-atomizer in React project created by create-react-app?

### ISSUE THREAD

**Issue by ammar-yasir** [acss-io/grunt-atomizer#44]
https://github.com/acss-io/atomizer/issues/350

I have created issue on 'atomizer' repository too.

**Comment by iamammar1** [comment]
Please review my code and let me know where I'm missing something.
https://codesandbox.io/s/elegant-gauss-d2txs

**Comment by redonkulus** [comment]
Code looks fine to me. Let us know if you have any other issues.
